# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

queue:
  name: Default

steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: others-update2'
  inputs:
    azureSubscription: 'dtlqa'

    WebAppName: 'AjyaApp'

    packageForLinux: 'C:\Users\suaggar\Asp4.zip'